name: Black Duck Intelligent Scan

on:
  pull_request:
    branches:
      - main
    schedule: 
      - cron: '5 23 * * *'
  # Allows you to run this workflow manually from the actions tab
  workflow_dispatch:
  
jobs:
  build:
  # The type of runner that the job will run on
   runs-on: ubuntu-latest
  
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - users: actions/checkout@v2
  
  # Setup JDK !! in runtime environment
  - name: Set Up JDK 11
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
    
    # Run Synopsys Detect
  - name: Run Synopsys Detect
    uses: synopsys-sig/detect-action@v0.1.0
    # this server does not require a local CA Cert.
    # If it did we would install the necessary CA Cert, supporting our self-signed server cert,
    # in a self-hosted runner and reference it here.
    #env:
    # NODE_EXTRA_CA_CERTS: /home/runner/my_custom_cert.pem
    with: 
      scan-mode: INTELLIGENT
      github-token: ${{ secrets.GITHUB_TOKEN }}
      detect-version: 8.11.0
      blackduck-url: ${{ secret.BLACKDUCK_URL }}
      blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
      
